### PR TITLE
Various fixes for Goerli deployment

### PR DESCRIPTION
**Pull request by pinebit**

### CODE REVIEW

**Review by bolekk — APPROVED** [review]
lgtm. @KuphJr  please take a look as well

**Comment by KuphJr** [comment]
I have included all the changes here in the `update-name` branch.  This PR can be closed.

**Comment by bolekk** [comment]
When it comes to this particular PR, the clean way to do it is to merge this one into main and later rebase any branches on top of it.

**Comment by KuphJr** [comment]
> When it comes to this particular PR, the clean way to do it is to merge this one into main and later rebase any branches on top of it.

Unfortunately I don't rebasing will work as intended due to all the file names changing.  I think merging the name change PR to `main` & doing code reviews for PRs to the `main` branch is the best option going forward

**Pull request closed without merging**
